# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/
# https://github.com/poole/poole/issues/99 suggests to disable the following:
#relative_permalinks: true

# Setup
title:            'o2r'
tagline:          'opening reproducible research'
description:      'Opening Reproducible Research is a <a href="https://www.dfg.de/en/" title="DFG website">DFG</a>-funded research project by Institute for Geoinformatics (<a href="https://www.uni-muenster.de/Geoinformatics/en/" title="ifgi website">ifgi</a>) and University and Regional Library (<a href="https://www.ulb.uni-muenster.de/" title="ULB website">ULB</a>), University of MÃ¼nster, Germany'
url:              'https://o2r.info'
baseurl:          ''

keywords:
  - open access
  - open data
  - open source
  - research data management
  - executable research
  - executable papers
  - one-click reproduce
  - executable research compendium
  - ERC
  - reproducibility
  - computational reproducibility

author:
  name:           'o2r Team'
  url:            https://o2r.info

paginate:         5

github:
  org:           https://github.com/o2r-project
twitter:
  url: https://twitter.com/o2r_project
  handle: '@o2r_project'

exclude: [README.md, CNAME, "Gemfile", "Gemfile.lock", "README.md", "Makefile", "vendor"]
# ribbon itself by https://github.com/simonwhitaker/github-fork-ribbon-css
ribbon:
  show:   true
  text:   'Join the pilots! ðŸš€'
  url:    '/pilots'

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  # https://github.com/jekyll/jekyll-redirect-from
  - jekyll-redirect-from
  # https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
